os:
  - linux
  - osx
dist: bionic
sudo: false
addons:
  apt:
    packages:
      # necessary for kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libiberty-dev
      - binutils-dev
      - cmake
      - gcc

language: rust
rust:
  - stable
  - nightly

stages:
  - name: test
  - name: lint

install: true

# Default script is the "test" stage
script: 
  - cargo build
  - cargo test

jobs:
  include:
    - stage: lint
      if: os = linux
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

cache: cargo
